version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: workspaces/api/Dockerfile
    container_name: gameNR_api
    ports:
      - "3000:3000"
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 4damantium!
      DATABASE_HOST: db       
      DATABASE_PORT: 5432
      DATABASE_NAME: BPGIT-DB 

    networks:
      - smart-network

  front:
    build:
      context: .
      dockerfile: workspaces/front/Dockerfile
    container_name: gameNR_front
    environment:
      - VITE_API_URL=http://url_cgi:3000/gameNR
    ports:
      - "8083:80"
    networks:
      - smart-network

networks:
  smart-network:
